Bistronger/Models/Items/ItemCreateViewModel.cs
using Bistronger.Data.Enums;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

/// <summary>
/// Stijn + Vic
/// </summary>
namespace Bistronger.Models.Items
{
    public class ItemCreateViewModel
    {
        [Required(ErrorMessage = "Naam dient correct ingevuld te zijn.")]
        [StringLength(30, ErrorMessage = "Naam mag maximaal 30 karakters bevatten.")]
        public string Name { get; set; }

        [StringLength(500, ErrorMessage = "Beschrijving mag maximaal 500 karakters bevatten.")]
        public string Description { get; set; }

        [Required(ErrorMessage = "Geen geldige prijs.")]
        [Range(0, Double.MaxValue, ErrorMessage = "Prijs moet een positief getal zijn.")]
        public decimal Price { get; set; }

        [Required]
        public ItemType Type { get; set; }

        public IFormFile DisplayPicture { get; set; }
    }
}

Bistronger/Models/Items/ItemDetailViewModel.cs
using Bistronger.Data.Enums;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

/// <summary>
/// Stijn + Vic
/// </summary>
namespace Bistronger.Models.Items
{
    public class ItemDetailViewModel
    {
        public int ID { get; set; }
        public string Email { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public ItemType Type { get; set; }
        public byte[] DisplayPicture { get; set; }
    }
}

Bistronger/Models/Items/ItemEditViewModel.cs
using Bistronger.Data.Enums;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

/// <summary>
/// Stijn + Vic
/// </summary>
namespace Bistronger.Models.Items
{
    public class ItemEditViewModel
    {
        [HiddenInput]
        public int ID { get; set; }

        [HiddenInput]
        public string OwnerID { get; set; }

        public string Email { get; set; }

        [Required(ErrorMessage = "Naam dient correct ingevuld te zijn.")]
        [StringLength(30, ErrorMessage = "Naam mag maximaal 30 karakters bevatten.")]
        public string Name { get; set; }

        [StringLength(500, ErrorMessage = "Beschrijving mag maximaal 500 karakters bevatten.")]
        public string Description { get; set; }

        [Required(ErrorMessage = "Geen geldige prijs.")]
        [Range(0, Double.MaxValue, ErrorMessage = "Prijs moet een positief getal zijn.")]
        public decimal Price { get; set; }

        [Required]
        public ItemType Type { get; set; }

        public byte[] DisplayPictureBytes { get; set; }

        public IFormFile DisplayPictureUpload { get; set; }
    }
}

Bistronger/Models/Items/ItemIndexViewModel.cs
using Bistronger.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

/// <summary>
/// Stijn + Vic
/// </summary>
namespace Bistronger.Models.Items
{
    public class ItemIndexViewModel
    {
        public DataSet<Item> Items { get; set; }
    }
}

Bistronger/Controllers/BistroDetailsController.cs
using Bistronger.Areas.Identity;
using Bistronger.Data;
using Bistronger.Data.Design;
using Bistronger.Data.Enums;
using Bistronger.Models;
using Bistronger.Models.Businesses;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Bistronger.Controllers
{

    public class BistroDetailsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IBusinessManager _businessManager;
        private readonly ISocialManager _socialManager;
        public BistroDetailsController(ApplicationDbContext context, IBusinessManager businessManager, ISocialManager socialManager)
        {
            _context = context;
            _businessManager = businessManager;
            _socialManager = socialManager;

        }

        public IActionResult Details(int? id)
        {

            if (id == null)
            {
                return NotFound();
            }

            var business = _businessManager.GetBusinessForDetails(id.Value);
            var social = _socialManager.GetSocialForBusiness(id.Value);



            if (business == null)
            {
                return NotFound();
            }
            BusinessDetailViewModel vm = new BusinessDetailViewModel
            {
                ID = business.ID,
                OwnerID = business.OwnerID,
                Name = business.Name,
                City = business.City,
                HouseNumber = business.HouseNumber,
                Street = business.Street,
                DisplayPicture = business.DisplayPicture,
                Type = business.Type,
                Zipcode = business.Zipcode,
                Omschrijving = business.Omschrijving,
                BusinessHours = _businessManager.GetBusinessHours(business.ID).Data.ToList(),
                SocialMedia = social
            };




            return View(vm);
        }
    }
}

Bistronger/Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Bistronger.Data;
using System.Security.Claims;
using Bistronger.Areas.Identity;
using Microsoft.AspNetCore.Identity;
using Bistronger.Data.Design;
using Bistronger.Models.Items;
using Microsoft.AspNetCore.Authorization;
using Bistronger.Data.Enums;
using System.IO;

namespace Bistronger.Controllers
{
    [Authorize]
    public class ItemsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IItemManager _itemManager;
        public readonly UserManager<ApplicationUser> _userManager;

        public ItemsController(ApplicationDbContext context, IItemManager itemManager, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _itemManager = itemManager;
            _userManager = userManager;
        }

        [AuthorizeRoles(UserRoleType.Admin, UserRoleType.RestaurantOwner)]
        // GET: Items
        public IActionResult Index()
        {
            //var applicationDbContext = _context.Items.Include(i => i.Owner);

            var indexVM = new ItemIndexViewModel
            {
                Items = _itemManager.GetItems()
            };
            return View(indexVM);
        }


        // GET: Items/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item = _itemManager.GetItem(id.Value);

            var vm = new ItemDetailViewModel
            {
                ID = item.ID,
                Email = item.Owner.Email,
                Description = item.Description,
                Name = item.Name,
                Price = item.Price,
                Type = item.Type,
                DisplayPicture = item.DisplayPicture
            };

            if (item == null)
            {
                return NotFound();
            }

            return View(vm);
        }

        [AuthorizeRoles(UserRoleType.RestaurantOwner)]
        // GET: Items/Create
        public IActionResult Create()
        {
            ViewData["OwnerID"] = User.FindFirstValue(ClaimTypes.NameIdentifier);
            ItemCreateViewModel vm = new ItemCreateViewModel();
            return View(vm);
        }

        // POST: Items/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AuthorizeRoles(UserRoleType.RestaurantOwner)]
        public IActionResult Create(ItemCreateViewModel model)
        {
            if (ModelState.IsValid)
            {
                var item = new Item
                {
                    Description = model.Description,
                    Name = model.Name,
                    Price = model.Price,
                    Type = model.Type,
                    OwnerID = User.FindFirstValue(ClaimTypes.NameIdentifier)
                };

                if (model.DisplayPicture != null)
                {
                    using (var ms = new MemoryStream())
                    {
                        model.DisplayPicture.CopyTo(ms);
                        item.DisplayPicture = ms.ToArray();
                    }
                }

                _itemManager.CreateItem(item);

                return RedirectToAction(nameof(Index));
            }

            ViewData["OwnerID"] = User.FindFirstValue(ClaimTypes.NameIdentifier);
            return View(model);
        }

        [AuthorizeRoles(UserRoleType.Admin, UserRoleType.RestaurantOwner)]
        // GET: Items/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item = _itemManager.GetItem(id.Value);
            if (item == null)
            {
                return NotFound();
            }
            ViewData["OwnerID"] = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var vm = new ItemEditViewModel
            {
                ID = item.ID,
                OwnerID = item.OwnerID,
                Email = item.Owner.Email,
                Description = item.Description,
                Name = item.Name,
                Price = item.Price,
                Type = item.Type,
                DisplayPictureBytes = item.DisplayPicture
            };

            return View(vm);
        }

        // POST: Items/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AuthorizeRoles(UserRoleType.Admin, UserRoleType.RestaurantOwner)]
        public IActionResult Edit(int id, ItemEditViewModel model)
        {
            if (id != model.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var item = new Item
                    {
                        ID = model.ID,
                        OwnerID = model.OwnerID,
                        Description = model.Description,
                        Name = model.Name,
                        Price = model.Price,
                        Type = model.Type,
                        DisplayPicture = model.DisplayPictureBytes
                    };

                    //If new image we need to overwrite it
                    if (model.DisplayPictureUpload != null)
                    {
                        using (var ms = new MemoryStream())
                        {
                            model.DisplayPictureUpload.CopyTo(ms);
                            item.DisplayPicture = ms.ToArray();
                        }
                    }

                    _itemManager.EditItem(item);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ItemExists(model.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["OwnerID"] = User.FindFirstValue(ClaimTypes.NameIdentifier);
            return View(model);
        }

        [AuthorizeRoles(UserRoleType.Admin, UserRoleType.RestaurantOwner)]
        // GET: Items/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item = _itemManager.GetItem(id.Value);

            if (item == null)
            {
                return NotFound();
            }

            return View(item);
        }

        // POST: Items/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [AuthorizeRoles(UserRoleType.Admin, UserRoleType.RestaurantOwner)]
        public ActionResult DeleteConfirmed(int id)
        {
            _itemManager.DeleteItem(id);
            return RedirectToAction(nameof(Index));
        }

        private bool ItemExists(int id)
        {
            return _context.Items.Any(e => e.ID == id);
        }
    }
}

Bistronger/Views/Items/Create.cshtml
@using Bistronger.Models.Items
@using Bistronger.Data.Enums

@model ItemCreateViewModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Creëer</h1>

<h4>Product</h4>
<hr />
<div class="row">
    <div class="col-md-8">
        <form enctype="multipart/form-data" asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label">Naam</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label">Beschrijving</label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label">Prijs</label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <select asp-for="Type" class="form-control">
                    @foreach (ItemType itemType in (ItemType[])Enum.GetValues(typeof(ItemType)))
                    {
                        if (itemType != ItemType.Unknown && itemType != ItemType.Advert)
                        {
                            <option>@itemType</option>
                        }
                    }
                </select>
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DisplayPicture">Afbeelding</label>
                <div class="custom-file">
                    <input asp-for="DisplayPicture" class="form-control custom-file-input" />
                    <label asp-for="DisplayPicture" class="custom-file-label">Kies bestand...</label>
                </div>
            </div>

            <div class="form-group">
                <input type="submit" value="Toevoegen" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Terug naar de lijst.</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Bistronger/Views/Items/Delete.cshtml
@model Bistronger.Data.Item

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Verwijderen</h1>

<h3>Bent u zeker dat u dit wenst te verwijderen?</h3>
<div>
    <h4>Product</h4>
    <hr />
    <div class="row">
        <dl class="row col-md-6">
            <dt class="col-sm-2">
                Naam
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Name)
            </dd>
            <dt class="col-sm-2">
                Beschrijving
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Description)
            </dd>
            <dt class="col-sm-2">
                Prijs
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Price)
            </dd>
            <dt class="col-sm-2">
                Type
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Type)
            </dd>
            <dt class="col-sm-2">
                Afbeelding:
            </dt>
            <dd class="col-sm-10">
                @if (Model.DisplayPicture != null)
                {
                    <img src="data:image;base64,@System.Convert.ToBase64String(Model.DisplayPicture)" alt="Image of business @Model.Name" class="main-business-picture" />
                }
                else
                {
                    <img src="~/res/img/noimage.png" alt="No picture" class="main-business-picture" />
                }
            </dd>
        </dl>
    </div>



    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Verwijderen" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Bistronger/Views/Items/Details.cshtml
@using Bistronger.Models.Items
@using Bistronger.Data.Enums

@model ItemDetailViewModel

@{
	ViewData["Title"] = "Details";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Product</h4>
    <hr />
    <div class="col-md-12 row">
        <dl class="row col-md-6">
            @if (User.IsInRole(UserRoleType.Admin.ToString()))
            {
                <dt class="col-sm-2">
                    Item ID:
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.ID)
                </dd>
                <dt class="col-sm-2">
                    Email:
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Email)
                </dd>
            }
            <dt class="col-sm-2">
                Naam
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Name)
            </dd>
            <dt class="col-sm-2">
                Beschrijving
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Description)
            </dd>
            <dt class="col-sm-2">
                Prijs
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Price)
            </dd>
            <dt class="col-sm-2">
                Type
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Type)
            </dd>
            <dt class="col-sm-2">
                Afbeelding:
            </dt>
            <dd class="col-sm-10">
                @if (Model.DisplayPicture != null)
                {
                    <a asp-controller="BistroDetails" asp-action="Details" asp-route-id="@Model.ID">
                        <img src="data:image;base64,@System.Convert.ToBase64String(Model.DisplayPicture)" alt="Image of business @Model.Name" class="card-img" />
                    </a>
                }
                else
                {
                    <a asp-controller="BistroDetails" asp-action="Details" asp-route-id="@Model.ID">
                        <img src="~/res/img/noimage.png" alt="No picture" class="card-img" />
                    </a>
                }
            </dd>
        </dl>
    </div>


</div>


@if (!User.IsInRole(UserRoleType.Customer.ToString()))
{
	<div>
		<a asp-action="Edit" asp-route-id="@Model.ID">Bewerken</a> |
		<a asp-action="Index">Terug naar de lijst.</a>
	</div>
}

Bistronger/Views/Items/Edit.cshtml
@using Bistronger.Models.Items
@using Bistronger.Data.Enums

@model ItemEditViewModel

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Product</h4>
<hr />
<div class="row">
    <div class="col-md-8">
        <form enctype="multipart/form-data" asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <input type="hidden" asp-for="OwnerID" />
            @if (User.IsInRole(UserRoleType.Admin.ToString()))
            {
                <div class="form-group col-md-3 pl-0">
                    <label class="control-label">Item ID: @Model.ID</label>
                </div>
                <div class="form-group col-md-3 pl-0">
                    <label class="control-label">Email: @Model.Email</label>
                </div>
            }
            <div class="form-group">
                <label asp-for="Name" class="control-label">Naam</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label">Beschrijving</label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label">Prijs</label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <select asp-for="Type" class="form-control">
                    @foreach (ItemType itemType in (ItemType[])Enum.GetValues(typeof(ItemType)))
                    {
                        if (itemType != ItemType.Unknown && itemType != ItemType.Advert)
                        {
                            <option>@itemType</option>
                        }
                    }
                </select>
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="hidden" asp-for="DisplayPictureBytes" />
                <label class="control-label">Afbeelding</label>

                @if (Model.DisplayPictureBytes != null)
                {
                    <img src="data:image;base64,@System.Convert.ToBase64String(Model.DisplayPictureBytes)" alt="Image of product @Model.Name"
                         class="card-img" />
                }
                else
                {
                    <img src="~/res/img/noimage.png" alt="No profile picture"
                         class="card-img" />
                }
            </div>
            <div class="form-group">
                <div class="custom-file">
                    <input asp-for="DisplayPictureUpload" class="form-control custom-file-input" />
                    <label asp-for="DisplayPictureUpload" class="custom-file-label">Kies bestand...</label>
                </div>
            </div>

            <div class="form-group">
                <input type="submit" value="Opslaan" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Terug naar de lijst.</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Bistronger/Views/Items/Index.cshtml
@using Bistronger.Models.Items
@using Bistronger.Data.Enums

@model ItemIndexViewModel

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1></h1>
<h1>Uw producten</h1>
@if (User.IsInRole(UserRoleType.RestaurantOwner.ToString()))
{
    <p>
        <a asp-action="Create">Crëeer een nieuw product.</a>
    </p>
}
<table class="table">
    <thead>
        <tr>
            @if (User.IsInRole(UserRoleType.Admin.ToString()))
            {
                <th>
                    ID
                </th>
                <th>
                    Email
                </th>
            }
            <th>
                Afbeelding
            </th>
            <th>
                Naam
            </th>
            <th>
                Beschrijving
            </th>
            <th>
                Prijs
            </th>
            <th>
                Type
            </th>
            <th>
                Handelingen
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Items.Data)
        {
            <tr>
                @if (User.IsInRole(UserRoleType.Admin.ToString()))
                {
                    <td class="align-middle">
                        @Html.DisplayFor(modelItem => item.ID)
                    </td>
                    <td class="align-middle">
                        @Html.DisplayFor(modelItem => item.Owner.Email)
                    </td>
                }
                <td class="align-middle">
                    @if (item.DisplayPicture != null)
                    {
                        <a asp-controller="Items" asp-action="Details" asp-route-id="@item.ID">
                            <img src="data:image;base64,@System.Convert.ToBase64String(item.DisplayPicture)" alt="Image of business @item.Name" class="main-business-picture rounded-circle m-0" style="height:150px;width:150px;" />
                        </a>
                    }
                    else
                    {
                        <a asp-controller="Items" asp-action="Details" asp-route-id="@item.ID">
                            <img src="~/res/img/noimage.png" alt="No picture" class="main-business-picture rounded-circle m-0" style="height:150px;width:150px;" />
                        </a>
                    }
                </td>
                <td class="align-middle">
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td class="align-middle">
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td class="align-middle">
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td class="align-middle">
                    @Html.DisplayFor(modelItem => item.Type)
                </td>
				<td class="align-middle">
					<a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
					<a asp-action="Details" asp-route-id="@item.ID">Details</a> |
					<a asp-action="Delete" asp-route-id="@item.ID">Verwijderen</a>
				</td>
            </tr>
        }
    </tbody>
</table>