Bistronger/Controllers/BistroDetailsController.cs
using Bistronger.Areas.Identity;
using Bistronger.Data;
using Bistronger.Data.Design;
using Bistronger.Data.Enums;
using Bistronger.Models;
using Bistronger.Models.Businesses;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Bistronger.Controllers
{

    public class BistroDetailsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IBusinessManager _businessManager;
        private readonly ISocialManager _socialManager;
        public BistroDetailsController(ApplicationDbContext context, IBusinessManager businessManager, ISocialManager socialManager)
        {
            _context = context;
            _businessManager = businessManager;
            _socialManager = socialManager;

        }

        public IActionResult Details(int? id)
        {

            if (id == null)
            {
                return NotFound();
            }

            var business = _businessManager.GetBusinessForDetails(id.Value);
            var social = _socialManager.GetSocialForBusiness(id.Value);



            if (business == null)
            {
                return NotFound();
            }
            BusinessDetailViewModel vm = new BusinessDetailViewModel
            {
                ID = business.ID,
                OwnerID = business.OwnerID,
                Name = business.Name,
                City = business.City,
                HouseNumber = business.HouseNumber,
                Street = business.Street,
                DisplayPicture = business.DisplayPicture,
                Type = business.Type,
                Zipcode = business.Zipcode,
                Omschrijving = business.Omschrijving,
                BusinessHours = _businessManager.GetBusinessHours(business.ID).Data.ToList(),
                SocialMedia = social
            };




            return View(vm);
        }
    }
}

Bistronger/Controllers/ReservationsController.cs
using Bistronger.Areas.Identity;
using Bistronger.Data;
using Bistronger.Data.Design;
using Bistronger.Data.Enums;
using Bistronger.Models;
using Bistronger.Models.Reservations;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

/// <summary>
/// Vic & Scott
/// </summary>
namespace Bistronger.Controllers
{
    public class ReservationsController : Controller
    {
        private readonly ApplicationDbContext _context;
        public readonly UserManager<ApplicationUser> _userManager;
        private readonly IOrderManager _orderManager;
        private readonly IBusinessManager _businessManager;
        private readonly IReservationManager _reservationManager;
        private readonly ITableManager _tableManager;

        public ReservationsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager,
            IOrderManager orderManager, IBusinessManager businessManager, IReservationManager reservationManager, ITableManager tableManager)
        {
            _context = context;
            _orderManager = orderManager;
            _businessManager = businessManager;
            _reservationManager = reservationManager;
            _userManager = userManager;
            _tableManager = tableManager;
        }

        [AuthorizeRoles(UserRoleType.Customer, UserRoleType.Admin, UserRoleType.RestaurantOwner)]
        public IActionResult Index(ReservationIndexViewModel vm)
        {
            if (vm == null)
            {
                return NotFound();
            }

            var indexVM = new ReservationIndexViewModel
            {
                Reservations = _reservationManager.GetReservations()
            };

            return View(indexVM);
        }

        // GET: Tables/Add
        [AuthorizeRoles(UserRoleType.Customer)]
        public IActionResult Create(int? businessID)
        {
            if (businessID == null || !businessID.HasValue)
            {
                return NotFound();
            }
            Business business = _businessManager.GetBusinessForDetails(businessID.Value);
            if (business == null)
            {
                return NotFound();
            }
            var addVM = new ReservationCreateViewModel
            {
                FoundTable = true,
                BusinessID = businessID.Value,
                BusinessToReserve = business,
                BusinessHours = _businessManager.GetBusinessHours(business.ID).Data,
            };

            return View(addVM);
        }

        // POST: Tables/ADD
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AuthorizeRoles(UserRoleType.Customer)]
        public IActionResult Create(ReservationCreateViewModel vm)
        {
            if (ModelState.IsValid)
            {
                string userID = User.FindFirstValue(ClaimTypes.NameIdentifier);
                Table table = _tableManager.GetFreeTable(vm.BusinessID, vm.AmountOfGuests, vm.ReservationDate.Value);
                if (table != null)
                {
                    Reservation newReservation = new Reservation
                    {
                        UserID = userID,
                        TableID = table.ID,
                        AmountOfGuests = vm.AmountOfGuests,
                        ReservationDateFrom = vm.ReservationDate,
                        ReservationDateTo = vm.ReservationDate.Value.AddHours(1)
                    };
                    _reservationManager.CreateReservation(newReservation);
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    vm.FoundTable = false;
                }
            }

            // Can't pass objects with vm -> opnieuw opvragen
            Business business = _businessManager.GetBusinessForDetails(vm.BusinessID);
            if (business == null)
            {
                return NotFound();
            }
            vm.BusinessToReserve = business;
            vm.BusinessHours = _businessManager.GetBusinessHours(vm.BusinessID).Data;
            return View(vm);
        }
    }
}

Bistronger/Views/BistroDetails/Details.cshtml
@using Bistronger.Models.Businesses
@model BusinessDetailViewModel

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    <a asp-controller="Reservations" asp-action="Create" asp-route-businessID="@Model.ID" class="btn btn-info">Reserveer uw tafel</a>
    <h2 class="text-center">@Html.DisplayFor(model => model.Name)</h2>
    <hr />
    <div class="row">
        <div class="col-md-6">
            <div>
                <h5 style="margin-left:50px;">Locatie</h5>
            </div>
            <dl class="row">
                <dt class="col-md-4">
                    Straatnaam:
                </dt>
                <dd class="col-md-8">
                    @Html.DisplayFor(model => model.Street)
                </dd>
                <dt class="col-md-4">
                    Huisnummer:
                </dt>
                <dd class="col-md-8">
                    @Html.DisplayFor(model => model.HouseNumber)
                </dd>
                <dt class="col-md-4">
                    Postcode:
                </dt>
                <dd class="col-md-8">
                    @Html.DisplayFor(model => model.Zipcode)
                </dd>
                <dt class="col-md-4">
                    Stad:
                </dt>
                <dd class="col-md-8">
                    @Html.DisplayFor(model => model.City)
                </dd>
            </dl>
        </div>
        <div class="col-md-6">

            <dl>
                <dt>
                </dt>
                <dd>
                    @if (Model.DisplayPicture != null)
                    {
                        <img src="data:image;base64,@System.Convert.ToBase64String(Model.DisplayPicture)" alt="Image of business @Model.Name" class="details-business-picture img-fluid rounded" />
                    }
                    else
                    {
                        <img src="~/res/img/noimage.png" alt="No picture" class="details-business-picture img-fluid rounded" />
                    }
                </dd>
            </dl>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
			<dl>
				<dt>
					Omschrijving:
				</dt>
				<dd class="text-break">
					@Html.DisplayFor(model => model.Omschrijving)
				</dd>
				<dt>Socials</dt>
				@if (Model.SocialMedia.Website == null && Model.SocialMedia.Facebook == null && Model.SocialMedia.Instagram == null && Model.SocialMedia.Twitter == null)
				{
					<dd>Geen socials beschikbaar.</dd>
				}
				else
				{
					if (Model.SocialMedia.Website != null)
					{
						<dd><a style="text-decoration:none" href="@Model.SocialMedia.Website">Website restaurant</a></dd>
					}

					if (Model.SocialMedia.Facebook != null)
					{
						<dd><a style="text-decoration:none" href="@Model.SocialMedia.Facebook"><i class="fa fa-facebook"></i></a></dd>
					}
					if (Model.SocialMedia.Instagram != null)
					{
						<dd><a style="text-decoration:none" href="@Model.SocialMedia.Instagram"><i class="fa fa-instagram"></i></a></dd>
					}
					if (Model.SocialMedia.Twitter != null)
					{
						<dd><a style="text-decoration:none" href="@Model.SocialMedia.Twitter"><i class="fa fa-twitter"></i></a></dd>
					}
				}
			</dl>
        </div>
        <div class="col-md-6">
            <h5>Openingsuren:</h5>
			<ul>
				@foreach (var item in Model.BusinessHours)
				{
					string hours = $"{item.Day}: {item.OpeningsHour.ToShortTimeString()} - {item.ClosingHour.ToShortTimeString()}";

					bool open = (TimeSpan.Compare(item.OpeningsHour.TimeOfDay, item.ClosingHour.TimeOfDay) == -1);

					if (open)
					{
						<li>@hours</li>
					}
					else
					{
						hours = $"{item.Day}: gesloten";
						<li>@hours</li>
					}
				}				
			</ul>
        </div>
    </div>
</div>