Bistronger/Models/Orders/OrderIndexViewModel.cs
using Bistronger.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Bistronger.Models.Orders
{
    public class OrderIndexViewModel
    {
        public DataSet<Order> Orders { get; set; }

    }
}

Bistronger/Controllers/BusinessesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Bistronger.Data;
using Bistronger.Data.Design;
using Bistronger.Models.Businesses;
using System.IO;
using Microsoft.AspNetCore.Identity;
using Bistronger.Areas.Identity;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Bistronger.Data.Enums;

/// <summary>
/// Stijn
/// </summary>
namespace Bistronger
{
    [Authorize]
    public class BusinessesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IBusinessManager _businessManager;
        private readonly ISocialManager _socialManager;
        public readonly UserManager<ApplicationUser> _userManager;
        private readonly IBusinessMenuManager _businessMenuManager;

        public BusinessesController(ApplicationDbContext context, IBusinessManager businessManager, ISocialManager socialManager, UserManager<ApplicationUser> userManager
            , IBusinessMenuManager businessMenuManager)
        {
            _context = context;
            _businessManager = businessManager;
            _socialManager = socialManager;
            _userManager = userManager;
            _businessMenuManager = businessMenuManager;
        }

        [AllowAnonymous]
        // GET: Businesses
        public IActionResult Index(int skipAmount, BusinessFilter filter)
        {
            if (filter == null)
                filter = new BusinessFilter();

            var indexVM = new BusinessIndexViewModel
            {
                Businesses = _businessManager.GetBusinesses(filter),
                Filter = filter
            };
            return View(indexVM);
        }

        [AuthorizeRoles(UserRoleType.Admin, UserRoleType.RestaurantOwner)]
        // GET: Businesses/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var business = _businessManager.GetBusiness(id.Value);
            var social = _socialManager.GetSocialForBusiness(id.Value);
            var busMenu = _businessMenuManager.GetBusinessMenuForBusiness(id.Value);

            if (business == null)
            {
                return NotFound();
            }
            BusinessDetailViewModel vm = new BusinessDetailViewModel
            {
                ID = business.ID,
                OwnerID = business.OwnerID,
                Email = business.Owner.Email,
                Name = business.Name,
                City = business.City,
                HouseNumber = business.HouseNumber,
                Mailbox = business.Mailbox,
                Street = business.Street,
                DisplayPicture = business.DisplayPicture,
                Type = business.Type,
                Zipcode = business.Zipcode,
                Omschrijving = business.Omschrijving,
                BusinessHours = _businessManager.GetBusinessHours(business.ID).Data.ToList(),
                SocialMedia = social,
                MenuID = busMenu != null ? busMenu.MenuID : 0
            };

            return View(vm);
        }

        [AuthorizeRoles(UserRoleType.RestaurantOwner)]
        // GET: Businesses/Create
        public IActionResult Create()
        {
            ViewData["OwnerID"] = User.FindFirstValue(ClaimTypes.NameIdentifier);
            BusinessCreateViewModel vm = new BusinessCreateViewModel();
            return View(vm);
        }

        // POST: Businesses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AuthorizeRoles(UserRoleType.RestaurantOwner)]
        public IActionResult Create(BusinessCreateViewModel model)
        {
            if (ModelState.IsValid)
            {
                var business = new Business
                {
                    OwnerID = User.FindFirstValue(ClaimTypes.NameIdentifier),
                    Name = model.Name,
                    Street = model.Street,
                    HouseNumber = model.HouseNumber,
                    Mailbox = model.Mailbox,
                    Zipcode = model.Zipcode,
                    City = model.City,
                    Type = model.Type,
                    Omschrijving = model.Omschrijving
                };

                if (model.DisplayPicture != null)
                {
                    using (var ms = new MemoryStream())
                    {
                        model.DisplayPicture.CopyTo(ms);
                        business.DisplayPicture = ms.ToArray();
                    }
                }

                var social = model.Social;
                social.Business = business;
                social.BusinessID = business.ID;

                _businessManager.CreateBusiness(business);
                _socialManager.CreateSocial(social);

                if ((model.MenuID != null) && model.MenuID.Value > 0)
                {
                    var busMenu = new BusinessMenu
                    {
                        BusinessID = business.ID,
                        MenuID = model.MenuID.Value
                    };
                    _businessMenuManager.CreateBusinessMenu(busMenu);
                }


                foreach (BusinessHour hour in model.BusinessHours)
                {
                    hour.BusinessID = business.ID;
                    _businessManager.AddBusinessHours(hour);
                }

                return RedirectToAction(nameof(Index));
            }
            ViewData["OwnerID"] = User.FindFirstValue(ClaimTypes.NameIdentifier);
            return View(model);
        }

        // GET: Businesses/Edit/5
        [AuthorizeRoles(UserRoleType.Admin, UserRoleType.RestaurantOwner)]
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var business = _businessManager.GetBusiness(id.Value);
            var social = _socialManager.GetSocialForBusiness(id.Value);
            var businessMenu = _businessMenuManager.GetBusinessMenuForBusiness(id.Value);
            if (business == null)
            {
                return NotFound();
            }
            ViewData["OwnerID"] = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var businesVM = new BusinessEditViewModel
            {
                ID = business.ID,
                OwnerID = business.OwnerID,
                Email = business.Owner.Email,
                Name = business.Name,
                Street = business.Street,
                HouseNumber = business.HouseNumber,
                Mailbox = business.Mailbox,
                Zipcode = business.Zipcode,
                City = business.City,
                Type = business.Type,
                DisplayPictureBytes = business.DisplayPicture,
                BusinessHours = _businessManager.GetBusinessHours(business.ID).Data.ToList(),
                Omschrijving = business.Omschrijving,
                Social = social,
                MenuID = businessMenu == null ? null : businessMenu.MenuID,
                SocialID = social.ID
            };

            if (businessMenu != null)
                businesVM.BusMenuID = businessMenu.ID;

            return View(businesVM);
        }

        // POST: Businesses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AuthorizeRoles(UserRoleType.Admin, UserRoleType.RestaurantOwner)]
        public IActionResult Edit(int id, BusinessEditViewModel model)
        {
            if (id != model.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var business = new Business
                {
                    ID = model.ID,
                    OwnerID = model.OwnerID,
                    Name = model.Name,
                    Street = model.Street,
                    HouseNumber = model.HouseNumber,
                    Mailbox = model.Mailbox,
                    Zipcode = model.Zipcode,
                    City = model.City,
                    Type = model.Type,
                    DisplayPicture = model.DisplayPictureBytes,
                    Omschrijving = model.Omschrijving
                };

                //If new image we need to overwrite it
                if (model.DisplayPictureUpload != null)
                {
                    using (var ms = new MemoryStream())
                    {
                        model.DisplayPictureUpload.CopyTo(ms);
                        business.DisplayPicture = ms.ToArray();
                    }
                }

                var social = model.Social;
                social.Business = business;
                social.BusinessID = business.ID;
                social.ID = model.SocialID;


                var busMenu = new BusinessMenu();


                if (model.MenuID > 0)
                {
                    busMenu.ID = model.BusMenuID;
                    busMenu.BusinessID = model.ID;
                    busMenu.MenuID = model.MenuID.Value;
                }

                try
                {
                    _businessManager.EditBusiness(business);
                    _socialManager.EditSocial(social);

                    //If a menu was selected we either edit or create one
                    if (model.MenuID != -1)
                    {
                        //if menu exists we edit it, else we create it

Bistronger/Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Bistronger.Data;
using System.Security.Claims;
using Bistronger.Areas.Identity;
using Microsoft.AspNetCore.Identity;
using Bistronger.Data.Design;
using Bistronger.Models.Items;
using Microsoft.AspNetCore.Authorization;
using Bistronger.Data.Enums;
using System.IO;

namespace Bistronger.Controllers
{
    [Authorize]
    public class ItemsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IItemManager _itemManager;
        public readonly UserManager<ApplicationUser> _userManager;

        public ItemsController(ApplicationDbContext context, IItemManager itemManager, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _itemManager = itemManager;
            _userManager = userManager;
        }

        [AuthorizeRoles(UserRoleType.Admin, UserRoleType.RestaurantOwner)]
        // GET: Items
        public IActionResult Index()
        {
            //var applicationDbContext = _context.Items.Include(i => i.Owner);

            var indexVM = new ItemIndexViewModel
            {
                Items = _itemManager.GetItems()
            };
            return View(indexVM);
        }


        // GET: Items/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item = _itemManager.GetItem(id.Value);

            var vm = new ItemDetailViewModel
            {
                ID = item.ID,
                Email = item.Owner.Email,
                Description = item.Description,
                Name = item.Name,
                Price = item.Price,
                Type = item.Type,
                DisplayPicture = item.DisplayPicture
            };

            if (item == null)
            {
                return NotFound();
            }

            return View(vm);
        }

        [AuthorizeRoles(UserRoleType.RestaurantOwner)]
        // GET: Items/Create
        public IActionResult Create()
        {
            ViewData["OwnerID"] = User.FindFirstValue(ClaimTypes.NameIdentifier);
            ItemCreateViewModel vm = new ItemCreateViewModel();
            return View(vm);
        }

        // POST: Items/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AuthorizeRoles(UserRoleType.RestaurantOwner)]
        public IActionResult Create(ItemCreateViewModel model)
        {
            if (ModelState.IsValid)
            {
                var item = new Item
                {
                    Description = model.Description,
                    Name = model.Name,
                    Price = model.Price,
                    Type = model.Type,
                    OwnerID = User.FindFirstValue(ClaimTypes.NameIdentifier)
                };

                if (model.DisplayPicture != null)
                {
                    using (var ms = new MemoryStream())
                    {
                        model.DisplayPicture.CopyTo(ms);
                        item.DisplayPicture = ms.ToArray();
                    }
                }

                _itemManager.CreateItem(item);

                return RedirectToAction(nameof(Index));
            }

            ViewData["OwnerID"] = User.FindFirstValue(ClaimTypes.NameIdentifier);
            return View(model);
        }

        [AuthorizeRoles(UserRoleType.Admin, UserRoleType.RestaurantOwner)]
        // GET: Items/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item = _itemManager.GetItem(id.Value);
            if (item == null)
            {
                return NotFound();
            }
            ViewData["OwnerID"] = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var vm = new ItemEditViewModel
            {
                ID = item.ID,
                OwnerID = item.OwnerID,
                Email = item.Owner.Email,
                Description = item.Description,
                Name = item.Name,
                Price = item.Price,
                Type = item.Type,
                DisplayPictureBytes = item.DisplayPicture
            };

            return View(vm);
        }

        // POST: Items/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AuthorizeRoles(UserRoleType.Admin, UserRoleType.RestaurantOwner)]
        public IActionResult Edit(int id, ItemEditViewModel model)
        {
            if (id != model.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var item = new Item
                    {
                        ID = model.ID,
                        OwnerID = model.OwnerID,
                        Description = model.Description,
                        Name = model.Name,
                        Price = model.Price,
                        Type = model.Type,
                        DisplayPicture = model.DisplayPictureBytes
                    };

                    //If new image we need to overwrite it
                    if (model.DisplayPictureUpload != null)
                    {
                        using (var ms = new MemoryStream())
                        {
                            model.DisplayPictureUpload.CopyTo(ms);
                            item.DisplayPicture = ms.ToArray();
                        }
                    }

                    _itemManager.EditItem(item);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ItemExists(model.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["OwnerID"] = User.FindFirstValue(ClaimTypes.NameIdentifier);
            return View(model);
        }

        [AuthorizeRoles(UserRoleType.Admin, UserRoleType.RestaurantOwner)]
        // GET: Items/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item = _itemManager.GetItem(id.Value);

            if (item == null)
            {
                return NotFound();
            }

            return View(item);
        }

        // POST: Items/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [AuthorizeRoles(UserRoleType.Admin, UserRoleType.RestaurantOwner)]
        public ActionResult DeleteConfirmed(int id)
        {
            _itemManager.DeleteItem(id);
            return RedirectToAction(nameof(Index));
        }

        private bool ItemExists(int id)
        {
            return _context.Items.Any(e => e.ID == id);
        }
    }
}

Bistronger/Views/Orders/Create.cshtml
@using Bistronger.Models.Orders
@using Bistronger.Data.Enums

@inject Bistronger.Data.Design.IMenuItemManager menuItemManager
@inject Bistronger.Data.Design.IBusinessMenuManager busMenuManager
@inject Bistronger.Data.Design.IBusinessManager businessManager


@model OrderCreateViewModel

@{
	ViewData["Title"] = "Create";
	Layout = "~/Views/Shared/_Layout.cshtml";
	var busHours = businessManager.GetBusinessHours(Model.BusinessID).Data;
	var business = businessManager.GetBusinessForDetails(Model.BusinessID);

}

<h1>Bestelling</h1>

@if (businessManager.GetBusinessOpenStatus(Model.BusinessID) == BusinessOpenStatus.Closed)
{
	<hr />
	<p>Deze bistro is momenteel gesloten, dus u kunt geen bestellingen plaatsen.</p>
	<p>Openingstijden voor <a asp-controller="BistroDetails" asp-action="Details" asp-route-id="@business.ID" target="_blank">@business.Name</a>:</p>
	<ul>
		@{
		}
		@foreach (var item in busHours)
		{
			string hours = $"{item.Day} {item.OpeningsHour.ToShortTimeString()} - {item.ClosingHour.ToShortTimeString()}";

			<li>@hours</li>
		}
	</ul>
}
else
{

	@if (Model.BusMenu != null)
	{
		<h4>Menu: @Model.BusMenu.Menu.Naam - Bistro: @Model.BusMenu.Business.Name</h4>
		<hr />
		<form asp-action="Create">
			<div class="row">
				<div class="col-md-6">
					<div asp-validation-summary="ModelOnly" class="text-danger"></div>
					<input type="hidden" asp-for="UserID" />
					<input type="hidden" asp-for="BusinessID" />
					<input type="hidden" asp-for="MenuItems" />

					@{int teller = 0;
					}
					@foreach (ItemType itemType in (ItemType[])Enum.GetValues(typeof(ItemType)))
					{
						if (itemType != ItemType.Unknown && itemType != ItemType.Advert)
						{
							<div class="d-flex justify-content-between">
								<h5>
									@EnumHelper.GetDisplayName(itemType)
								</h5>
								<h5 class="float-right">Credits</h5>

							</div>
							<hr class="hrMenu" />

							<div class="form-group">
								@{int itemFound = 0;

								}

								@foreach (var item in Model.MenuItems)
								{
									if
										(item.Item.Type == itemType)
									{
										itemFound++;

										<div class="form-group">
											<input hidden asp-for="OrderLines[teller].ItemID" value="@item.Item.ID" />
											<input asp-for="OrderLines[teller].Amount"
												   class="form-control col-md-2 orderAmount" style="display:inline-flex" type="number"
												   step="1" min="0" oninput="checkForButton()" itemName="@item.Item.Name" itemPrice="@item.Item.Price"
												   onkeypress="return event.keyCode === 8 || event.charCode >= 48 && event.charCode <= 57 || event.charCode >= 0 && event.charCode <= 9" />
											<a class="control-label pl-2" asp-action="Details" asp-controller="Items" asp-route-id=@item.Item.ID target="_blank">@item.Item.Name</a>
											<label class="control-label pl-2 float-right mt-3">@item.Item.Price</label>
											<span asp-validation-for="OrderLines[teller].Amount" class="text-danger"></span>
										</div>
										teller++;
									}
								}

								@if (itemFound == 0)
								{
									<p>Niet aanwezig op menu.</p>
								}
							</div>
						}
					}

					<div class="form-group">
						<input type="submit" value="Plaats order" class="btn btn-primary" id="submitButton" disabled />
						<a asp-action="Index" asp-controller="Businesses">Terug naar Bistros</a>
					</div>
				</div>

				<div class="col-md-6 pl-5">
					<div class="d-flex justify-content-between">
						<h5>Bestelling details</h5>
						<h5>Credits</h5>
					</div>
					<hr class="hrMenu" />

					<div id="containerDetails">
						<p>Geen items geselecteerd.</p>
					</div>
					<hr class="hrMenu" />
					<div class="d-flex justify-content-between" id="containerTotal">
						<p style="font-weight:bold;font-size:1.3rem">Totaal</p>
						<p style="font-weight:bold;font-size:1.3rem" id="totalPrice">0,00</p>
					</div>
				</div>
			</div>
		</form>
	}
	else
	{
		<hr />
		<p>Menu niet beschikbaar.</p>

		<div class="form-group">
			<a asp-action="Index" asp-controller="Businesses">Terug naar Bistros</a>
		</div>
	}
}

@section Scripts {
	@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

	<script>

		function checkForButton() {
			if (isEveryInputEmpty()) {
				document.getElementById('submitButton').disabled = true;
			} else {
				document.getElementById('submitButton').disabled = false;
			}

			calculateDetails();
		}

		//https://stackoverflow.com/questions/26931755/check-if-all-inputs-are-empty/26931859
		function isEveryInputEmpty() {
			var allEmpty = true;
			$(".orderAmount").each(function () {
				if ($(this).val() !== "0" && $(this).val() !== "") {
					allEmpty = false;
					return false; // we've found a non-empty one, so stop iterating
				}
			});

			return allEmpty;
		}

		function calculateDetails() {
			$('#containerDetails').text("");
			var totalPrice = 0;

			$(".orderAmount").each(function () {
				if ($(this).val() !== "0" && $(this).val() !== "") {

					var amount = $(this).val();
					var itemName = $(this).attr("itemName");
					var price = $(this).attr("itemPrice").replace(',', '.');
					var totalPriceItem = amount * price;
					totalPrice += totalPriceItem;

					$('#containerDetails').append('<div class="d-flex justify-content-between"><p>' + amount + 'x ' + itemName + '</p><p>' + totalPriceItem.toFixed(2).replace('.', ',') + '</p></div>');
				}
			});

			if ($('#containerDetails').children().length == 0) {
				$('#containerDetails').text("Geen items geselecteerd.");
			}

			$('#totalPrice').text(totalPrice.toFixed(2).replace('.', ','));
		}
	</script>
}

Bistronger/Views/Orders/Delete.cshtml
@using Bistronger.Data.Enums
@using Bistronger.Models.Orders

@model OrderDetailViewModel

@{
	ViewData["Title"] = "Details";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Annuleren</h1>
<h3>Zeker dat je dit order wilt annuleren?</h3>

<div>
	<h4>Order</h4>
	<hr />
	<dl class="row">
		@*<dt class="col-sm-2">
				@Html.DisplayNameFor(model => model.User)
			</dt>
			<dd class="col-sm-10">
				@Html.DisplayFor(model => model.User.UserName)
			</dd>*@
		<dt class="col-sm-2">
			Type bestelling:
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.OrderType)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Status):
		</dt>
		<dd class="col-sm-10">
			@{
				var dispName = @EnumHelper.GetDisplayName(Model.Status);
			}
			@switch (Model.Status)
			{
				case OrderStatus.Finished:
					<span class="badge badge-pill badge-success">@dispName</span>
					break;
				case OrderStatus.Unpaid:
					<span class="badge badge-pill badge-warning">@dispName</span>
					break;
				case OrderStatus.InProgress:
					<span class="badge badge-pill badge-info">@dispName</span>
					break;
				case OrderStatus.Cancelled:
					<span class="badge badge-pill badge-danger">@dispName</span>
					break;
			}
		</dd>
		<dt class="col-sm-2">
			Aangemaakt op:
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.CreatedOn)
		</dd>
	</dl>
	<hr />
	<div class="row">
		<div class="col-md-6">
			@{
				decimal totalPrice = 0.0m;
			}

			@foreach (ItemType itemType in (ItemType[])Enum.GetValues(typeof(ItemType)))
			{
				if (itemType != ItemType.Unknown && itemType != ItemType.Advert)
				{
					if (Model.OrderLines.Any(m => m.Item.Type == itemType))
					{
						<div class="d-flex justify-content-between">
							<h5>
								@EnumHelper.GetDisplayName(itemType)
							</h5>
							<h5 class="float-right">Credits</h5>
						</div>
						<hr class="hrMenu" />

						decimal subtotaalCategorie = 0.0m;


						@foreach (var item in Model.OrderLines)
						{
							if
								(item.Item.Type == itemType)
							{
								<div class="d-flex justify-content-between">
									@{
										var totalItemPrice = item.Amount * item.Item.Price;
										subtotaalCategorie += totalItemPrice.Value;
									}
									<div>
										<label>@item.Amount x</label>
										<a asp-action="Details" asp-controller="Items" asp-route-id=@item.Item.ID target="_blank">@item.Item.Name</a>
									</div>
									<div>
										<label>@totalItemPrice</label>
									</div>
								</div>
							}
						}
						totalPrice += subtotaalCategorie;


						<div class="d-flex justify-content-between">
							<p style="font-weight:bold">Subtotaal</p>
							<p style="font-weight:bold">@subtotaalCategorie</p>
						</div>
					}
				}
			}
			<div class="d-flex justify-content-between">
				<p style="font-weight:bold;font-size:1.3rem">Totaal</p>
				<p style="font-weight:bold;font-size:1.3rem">@totalPrice</p>
			</div>
		</div>
	</div>
</div>

<form asp-action="Delete">
	<input type="hidden" asp-for="ID" />
	<input type="submit" value="Annuleer" class="btn btn-danger" /> |
	<a asp-action="Index">Terug naar overzicht</a>
</form>

Bistronger/Views/Orders/Edit.cshtml
@model Bistronger.Data.Order

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Order</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="UserID" class="control-label"></label>
                <select asp-for="UserID" class="form-control" asp-items="ViewBag.UserID"></select>
                <span asp-validation-for="UserID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OrderType" class="control-label"></label>
                <select asp-for="OrderType" class="form-control"></select>
                <span asp-validation-for="OrderType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <select asp-for="Status" class="form-control"></select>
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}